---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.podinfod: semver:~1.7
  name: backend
  namespace: team1
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: podinfod
      containers:
      - image: quay.io/stefanprodan/podinfo:1.7.4
        name: podinfod
        ports:
          - containerPort: 9899
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.podinfod: semver:~1.7
  name: frontend
  namespace: team1
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: podinfod
      containers:
      - $setElementOrder/ports:
        - containerPort:9899
        command:
        - ./podinfo
        - --port=9898
        - --level=info
        - --random-delay=false
        - --random-error=false
        - --backend-url=http://backend:9899/echo
        livenessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9899/healthz
        name: podinfod
        ports:
        - containerPort: 9899
          name: http
          protocol: TCP
        - $patch: delete
          containerPort: 9898
        readinessProbe:
          exec:
            command:
            - podcli
            - check
            - http
            - localhost:9898/readyz

